### ISSUE TITLE
npm-link-better --copy does not handle npm prefix

### ISSUE THREAD

**Issue by bodograumann** [laggingreflex/npm-link-better#4]
I have setup a prefix in my `.npmrc`:

> prefix=/home/bodo/.local

When I then try to use `npm-link-better --copy`, it tries to access `~/.local/node_modules/package-name`. Instead it should look in `~/.local/lib64/node_modules/package-name`.

**Comment by laggingreflex** [comment]
Why `lib64` isn't obvious to me, could you explain? 

Also to me it seems like it *should* look in `/home/bodo/.local` if that's what you've set in your `.npmrc`, no? Although I'm not entirely sure what this setting does. I am however using the command `npm config get prefix` to get the [prefix directory](https://docs.npmjs.com/files/folders#prefix-configuration) (in which npm seems to store global modules)

**Comment by bodograumann** [comment]
I can only tell you what I see on my system. (Gentoo Linux with npm 6.4.1 and node v8.12.0)

By default `npm get prefix` returns `/usr`. Then `npm install --global` would try to install into `/usr/lib64/node_modules`. E.g. as unprivileged user I get

> npm WARN checkPermissions Missing write access to /usr/lib64/node_modules

So when I set the prefix to `~/.local`, npm will install into `~/.local/lib64/node_modules`.

**Comment by laggingreflex** [comment]
Does `npm root -g` command give the correct path?

**Comment by laggingreflex** [comment]
Fixed using [global-prefix](https://github.com/jonschlinkert/global-prefix). Try v0.4.1

**Comment by bodograumann** [comment]
No, that did not fix the issue. Maybe you should use [global-modules](https://www.npmjs.com/package/global-modules) instead⁉

**Comment by laggingreflex** [comment]
Alright, good call. Try 0.4.2

**Comment by bodograumann** [comment]
Almost :-D. I had to create a symlink `~/.local/lib -> ~/.local/lib64` as a workaround. Cf. https://github.com/jonschlinkert/global-modules/issues/11

Thank you for the quick work.
